### ISSUE TITLE
ImportError: cannot import name 'log' -> (module: scheduler)

### ISSUE THREAD

**Issue by ivanleoncz** [ivanlmj/PyCaptive#11]
Traceback (most recent call last):
  File "pycaptive_werkzeug.py", line 15, in <module>
    from app import app
  File "/home/ivanlmj/git/PyCaptive/app/__init__.py", line 5, in <module>
    from app.modules import scheduler
  File "/home/ivanlmj/git/PyCaptive/app/modules/scheduler.py", line 15, in <module>
    from app import log
ImportError: cannot import name 'log'

**Comment by ivanleoncz** [comment]
Fixed!

https://github.com/ivanlmj/PyCaptive/commit/352ca7b97000f239aa392ddca345bac83f365265
